### ISSUE TITLE
error: Uncaught error stack=Error: spawn ENOENT

### ISSUE THREAD

**Issue by LogIN-** [einaros/http-tunnel#2]
Hi,
i configured nginx to serve http-tunnel.... anyway server is working fine but when i try to connect client to it on client i am getting following error:

```
2014-08-15T12:38:33.936Z - info: Secure connection established with tunnel server.
2014-08-15T12:38:33.944Z - info: Serving content through: http://test.xxx.com
2014-08-15T12:38:33.951Z - error: Uncaught error stack=Error: spawn ENOENT
    at exports._errnoException (util.js:742:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1028:32)
    at child_process.js:1109:20
    at process._tickCallback (node.js:343:11), code=ENOENT, errno=ENOENT, syscall=spawn, stack=Error: spawn ENOENT
    at exports._errnoException (util.js:742:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1028:32)
    at child_process.js:1109:20
    at process._tickCallback (node.js:343:11)
```

or without "uncaughtException" : 

```
....
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn ENOENT
    at exports._errnoException (util.js:742:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1028:32)
    at child_process.js:1109:20
    at process._tickCallback (node.js:343:11)
```

my best guess its node problem, does anybody have any idea how to make it work, or anything else???

**Comment by LogIN-** [comment]
It seems pbcopy spawn was  troubling
